{"name": "test_login_noExistUser_wrongPasswd[data1]", "status": "passed", "attachments": [{"name": "log", "source": "83d73802-b0ac-41b4-9364-2beb433c6d4e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'用户名': 'dsadsadsa', '密码': 'pytho', '预期': '请输入至少6位数的密码'}"}], "start": 1587375203743, "stop": 1587375204659, "uuid": "8bdded23-74ae-4957-87d7-6e1d740b1d60", "historyId": "47e3f1e986e05b42846028b7ee1e1bcc", "testCaseId": "5a65c10c865bdd3f50e0040d88be9f16", "fullName": "TestCases.test_02_ptsdList.TestLogin#test_login_noExistUser_wrongPasswd", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_02_ptsdList"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-O2A05I4"}, {"name": "thread", "value": "17492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_02_ptsdList"}]}